# from tkinter import*

# root=Tk()
# q=Button(root,text="(").grid(row=4,column=12)
# r=Button(root,text=")").grid(row=4,column=13)
# s=Button(root,text="%").grid(row=4,column=14)
# t=Button(root,text="CE").grid(row=4,column=15)
# a=Button(root,text="7").grid(row=6,column=12)
# b=Button(root,text="8").grid(row=6,column=13)
# c=Button(root,text="9").grid(row=6,column=14)
# d=Button(root,text="+").grid(row=6,column=15)
# e=Button(root,text="4").grid(row=8,column=12)
# f=Button(root,text="5").grid(row=8,column=13)
# g=Button(root,text="6").grid(row=8,column=14)
# h=Button(root,text="-").grid(row=8,column=15)
# i=Button(root,text="1").grid(row=10,column=12)
# j=Button(root,text="2").grid(row=10,column=13)
# k=Button(root,text="3").grid(row=10,column=14)
# l=Button(root,text="*").grid(row=10,column=15)
# m=Button(root,text="0").grid(row=12,column=12)
# n=Button(root,text=".").grid(row=12,column=13)
# o=Button(root,text="=").grid(row=12,column=14)
# p=Button(root,text="/").grid(row=12,column=15)

# root.mainloop()